<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery-1.11.1.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/TweenMax.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/plugins/ScrollToPlugin.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/ScrollMagic/scrollmagic-2.0.5.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/ScrollMagic/plugins/animation.gsap.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.fitvids-1.1.0.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.unveil.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/owl.carousel-2.0.0.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/slick.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/underscore-1.6.0.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/clamp-0.5.1.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/gnublog.main.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/gnublog.blog-single.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/gnublog.blog.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/gnublog.search-results.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/gnublog.search.js"></script>
